meta_product_name: "Solve It"
meta_title: "Solve It - IT Support on demand"
meta_description: "Solve your It issues on minutes! Schedule an On Demand appointment with one of our expert technicians"
meta_image: "meta_image.png" # should exist in `app/assets/images/`
